INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (1, 'افتتاح سپرده‌ي حقيقي - انتقالي', 'سپرده ها', 'D-10-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (2, 'افتتاح سپرده حقوقي - انتقالي', 'سپرده ها', 'D-10-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (3, 'افتتاح سپرده نزد بانک - انتقالي', 'سپرده ها', 'D-10-12', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (4, 'واريز به سپرده - واگذاري چک - کارمزد انتقالي', 'سپرده ها', 'D-11-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (5, 'واريز به سپرده - وصول چک', 'سپرده ها', 'D-11-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (6, 'صدور سند', 'حسابداري', 'A-19-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (7, 'برداشت از سپرده - با چک پاياپاي', 'سپرده ها', 'D-12-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (8, 'برداشت از سپرده - پرداخت قسمتي ازوجه - با چک پاياپاي', 'سپرده ها', 'D-12-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (9, 'صدور دسته چک - هزينه انتقالي', 'سپرده ها', 'D-18-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (10, 'برداشت از سپرده - صدور چک', 'سپرده ها', 'D-12-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (11, 'برداشت از سپرده - پرداخت قسمتي ازوجه - صدور چک', 'سپرده ها', 'D-12-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (12, 'انسداد سپرده - موجودي', 'سپرده ها', 'D-13-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (13, 'انسداد سپرده - رفع انسداد دستور پرداخت', 'سپرده ها', 'D-13-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (14, 'بستن سپرده - انتقالي', 'سپرده ها', 'D-14-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (15, 'صدور دفترچه سپرده - کارمزد انتقالي', 'سپرده ها', 'D-16-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (16, 'صدور برگ سپرده - هزينه ابطال تمبر انتقالي', 'سپرده ها', 'D-17-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (17, 'صدور دستور پرداخت - کارمزد انتقالي', 'سپرده ها', 'D-18-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (18, 'انتقال وجه', 'سپرده ها', 'D-20-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (19, 'صدور حواله - به ساير شعب', 'سپرده ها', 'D-21-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (20, 'صدور حواله - به ساير بانکها', 'سپرده ها', 'D-21-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (21, 'صدور سند پرداخت حواله وارده', 'سپرده ها', 'D-22-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (22, 'ثبت حواله وارده', 'سپرده ها', 'D-22-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (23, 'عمليات ارزي - خريد ارز', 'سپرده ها', 'D-30-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (24, 'عمليات ارزي - فروش ارز', 'سپرده ها', 'D-30-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (25, 'مديريت سود سپرده- واريز علي الحساب', 'سپرده ها', 'D-31-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (26, 'صدور حواله', 'سپرده ها', 'D-21-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (27, 'حوالجات', 'سپرده ها', 'D-22-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (28, 'عمليات خودکار اندوخته', 'سپرده ها', 'D-23-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (29, 'افتتاح خودکار سپرده بلندمدت اندوخته - انتقالي', 'سپرده ها', 'D-23-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (30, 'عمليات ارزي', 'سپرده ها', 'D-30-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (31, 'انتقال وجه مستقيم سپرده به سپرده', 'سپرده ها', 'D-20-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (32, 'انسداد سپرده - رفع انسدادموجود', 'سپرده ها', 'D-13-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (33, 'انسداد سپرده - رفع انسدادسپرده', 'سپرده ها', 'D-13-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (34, 'عمليات ارزي - تسعير', 'سپرده ها', 'D-30-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (35, 'صدور سند تسويه', 'حسابداري', 'A-46-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (36, 'پرداخت چک بين بانکي وارده', 'سپرده ها', 'D-96-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (37, 'انتقال وجه خودکار-انتقال وجه-قديمي', 'سپرده ها', 'D-98-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (38, 'صدور اسناد مشخص', 'حسابداري', 'A-61-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (39, 'انتقال رسوب از سپرده پشتيبان به سپرده اصلي', 'سپرده ها', 'D-103-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (40, 'صدور دستور پرداخت - کار مزد انتقالي', 'سپرده ها', 'D-81-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (41, 'صدور دسته چک - هزينه انتقالي', 'سپرده ها', 'D-81-11', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (42, 'اعمال نتيجه چکهاي ما', 'سپرده ها', 'D-80-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (43, 'عمليات خزانه داري - دريافت وجه نقد از ساير بانک ها', 'حسابداري', 'A-37-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (44, 'عمليات خزانه داري-تسويه وجوه درراه ارسالي به ساير شعب', 'حسابداري', 'A-37-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (45, 'صدور سند به تاريخ گذشته', 'حسابداري', 'A-39-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (46, 'وثائق مشتري-اضافه', 'مشتريان', 'C-30-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (47, 'وثايق مشتري-صدور سند بيمه', 'مشتريان', 'C-30-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (48, 'وثايق مشتري - صدور سند ارزيابي', 'مشتريان', 'C-30-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (49, 'وثائق مشتري-اصلاح سند بيمه', 'مشتريان', 'C-30-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (50, 'وثائق مشتري-اصلاح سند ارزيابي', 'مشتريان', 'C-30-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (51, 'وثايق مشتري - انتقال وثيقه به شعبه ديگر', 'مشتريان', 'C-30-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (52, 'جستجوي اعلاميه', 'حسابداري', 'A-67-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (53, 'اعلاميه/صدور', 'حسابداري', 'A-67-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (54, 'اعلاميه/ثبت', 'حسابداري', 'A-67-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (55, 'سود گواهي سپرده-واريز', 'سپرده ها', 'D-102-17', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (56, 'انتقال وجه بين حساب و سپرده', 'سپرده ها', 'D-110-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (57, 'صدور سند کلر', 'حسابداري', 'A-69-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (58, 'بستن خودکار سپرده بلندمدت اندوخته - انتقالي', 'سپرده ها', 'D-14-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (59, 'بستن خودکار سپرده بلندمدت اندوخته - آماده سازي حساب سود علي الحساب', 'سپرده ها', 'D-14-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (60, 'مديريت سود سپرده- واريز سود-دستي', 'سپرده ها', 'D-31-12', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (61, 'مديريت سود سپرده- برداشت سود-دستي', 'سپرده ها', 'D-31-13', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (62, 'سند موقت', 'حسابداري', 'A-81-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (63, 'صدور سند موقت', 'حسابداري', 'A-81-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (64, 'عمليات ارزي - تبديل ارز', 'سپرده ها', 'D-30-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (65, 'عمليات ارزي  - تبديل ارز با نرخ توافقي', 'سپرده ها', 'D-30-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (66, 'دريافت - صدور سند برگشت پيام ارسال شده', 'ساتنا', 'Q-13-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (67, 'دريافت - صدور سند پيام وارده MQ103', 'ساتنا', 'Q-13-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (68, 'عمليات روزانه-عمليات پايان روز', 'ساتنا', 'Q-15-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (69, 'مديريت دستور پرداخت - ثبت دستور پرداخت', 'پايا', 'p-4-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (70, 'پردازش صادره', 'پايا', 'p-7-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (71, 'دريافت - صدور سند پيام وارده MQ202', 'ساتنا', 'Q-13-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (72, 'تجديد/تمديد سپرده', 'سپرده ها', 'D-14-8', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (73, 'پردازش وارده', 'پايا', 'p-3-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (74, ' پردازش وارده - واريز گروهي', 'پايا', 'p-3-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (75, 'ثبت دستور پرداخت', 'ساتنا', 'Q-20-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (76, 'صدور سند فايلي', 'حسابداري', 'A-127-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (77, 'صدور سند فايلي به تاريخ روز', 'حسابداري', 'A-127-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (78, 'عمليات ارزي - خريد و فروش با نرخ توافقي', 'سپرده ها', 'D-30-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (79, 'عمليات ارزي - خريد و فروش با نرخ مصوب تاريخ گذشته', 'سپرده ها', 'D-30-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (80, 'عمليات پايان روز', 'ساتنا', 'Q-22-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (81, 'پردازش پيام وارده', 'ساتنا', 'Q-23-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (82, 'عمليات ابتداي روز', 'ساتنا', 'Q-24-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (83, 'عمليات دستور پرداخت جمعي-ثبت در شعبه', 'پايا', 'p-11-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (84, 'توليد رمز و پرفراژ اعلاميه', 'حسابداري', 'A-67-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (85, ' صدور سند فايلي ويژه سامان کارت', 'حسابداري', 'A-127-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (86, 'صدور سند فايلي به تاريخ گذشته بدون درگير شدن حساب مرکز', 'حسابداري', 'A-127-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (87, 'تسويه مانده حساب نتيجه مبادلات ارزي شعب', 'حسابداري', 'A-143-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (88, 'تسويه مانده حساب نتيجه مبادلات ارزي شعب-صدور سند', 'حسابداري', 'A-143-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (89, 'پردازش پيام صادره', 'ساتنا', 'Q-23-8', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (90, 'عمليات ارسال دريافت - عدم ارسال بازگشت به تاييد شعبه', 'ساتنا', 'Q-23-9', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (91, 'عمليات ارسال دريافت - عدم ارسال بازگشت به تاييد ساتنا', 'ساتنا', 'Q-23-10', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (92, 'گزارش دريافت ها و پرداخت هاي ارزي', 'حسابداري', 'A-139-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (93, 'گزارش دريافت ها و پرداخت هاي ارزي-گزارش', 'حسابداري', 'A-139-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (94, 'گزارش دريافت ها و پرداخت هاي ارزي-توليد فايل', 'حسابداري', 'A-139-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (95, 'انسداد سپرده - رفع انسداد سپرده - تغيير عامل مسدود کننده', 'سپرده ها', 'D-13-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (96, 'انتقال وجه از حساب به سپرده', 'سپرده ها', 'D-110-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (97, 'انتقال وجه از سپرده به حساب', 'سپرده ها', 'D-110-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (98, 'صدور سند کارمزد-انتقالي از سپرده يا حساب مطالبات سپرده به حساب کارمزد بانک', 'سپرده ها', 'D-168-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (99, 'کارمزد - برگشت سند دريافت کارمزد', 'سپرده ها', 'D-168-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (100, 'صدور سند تسويه کارمزد آفلاين', 'سپرده ها', 'D-168-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (101, 'ثبت چک  -برگشت اسناد گروه چک رمزدار', 'کلر الکترونيک', 'q-1-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (102, ' عمليات شعبه - نقد چک', 'کلر الکترونيک', 'q-2-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (103, ' عمليات شعبه - توازن حساب واسط شعبه', 'کلر الکترونيک', 'q-2-6', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (104, 'عمليات شعبه - پرداخت چک رمزدار واگذاري', 'کلر الکترونيک', 'q-2-9', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (105, 'عمليات شعبه - صدور دسته  چک رمزدار', 'کلر الکترونيک', 'q-2-10', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (106, ' عمليات شعبه سرپرستي - اعلام نقد چکهاي واگذاري', 'کلر الکترونيک', 'q-3-8', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (107, 'پرداخت حقوق شرکتها', 'سپرده ها', 'D-34-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (108, 'عمليات شعبه- جستجوي امضا مسئولين', 'کلر الکترونيک', 'q-2-13', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (109, 'بستن سپرده - نقدي/انتقالي', 'سپرده ها', 'D-14-11', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (110, 'بستن گروهي سپرده', 'سپرده ها', 'D-14-12', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (111, 'رفع انسداد سپرده - بين شعبه‌اي', 'سپرده ها', 'D-13-9', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (112, 'انسداد سپرده - بين شعبه‌اي', 'سپرده ها', 'D-13-8', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (113, 'رفع انسداد موجودي سپرده از مرکز', 'سپرده ها', 'D-13-13', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (114, 'رفع انسداد سپرده از مرکز', 'سپرده ها', 'D-13-11', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (115, 'بستن سپرده بين شعبه اي', 'سپرده ها', 'D-14-10', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (116, 'افتتاح سپرده براي مشتريان در ليست سياه', 'سپرده ها', 'D-10-17', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (117, 'تسويه وجوه در راه دريافتي از ساير بانک ها - تسويه به حساب ديگر', 'حسابداري', 'A-37-11', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (118, 'برگشت سند ساير شعب', 'حسابداري', 'A-20-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (119, 'برداشت از سپرده - نقد کردن چک', 'سپرده ها', 'D-12-10', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (120, 'مديريت دستور پرداخت - ثبت همزاد', 'پايا', 'p-4-13', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (121, 'خريد چک رمز دار در شعبه, واريز به سپرده مشتري', 'چکاوک', 'k-1-10', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (122, 'عمليات چکهاي وارده در شعبه, نقد چک', 'چکاوک', 'k-3-2', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (123, 'عمليات مرکز , اعلام نقد چک', 'چکاوک', 'k-4-1', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (124, 'واريز گروهي سود قطعي', 'سپرده ها', 'D-157-84', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (125, 'پرداخت سود قطعي اوراق نو/بازخريد/تسويه', 'سپرده ها', 'D-157-86', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (126, 'فروش چک رمز دار در شعبه, برداشت از سپرده مشتري براي صدور رمز دار', 'چکاوک', 'k-2-3', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (127, 'برداشت از سپرده - نقد کردن چک برگشتي به صورت انتقالي', 'سپرده ها', 'D-12-14', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (128, 'برداشت از سپرده - نقد کردن چک برگشتي', 'سپرده ها', 'D-12-11', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (129, 'مديريت دستورپرداخت - برداشت با سند جمعي', 'پايا', 'p-4-14', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (130, 'چک تضميني - ثبت برگ چک', 'سپرده ها', 'D-191-2', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (131, 'چک تضميني - صدور برگ چک', 'سپرده ها', 'D-191-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (132, 'ثبت چک بين بانکي چکاوک', 'سپرده ها', 'D-96-20', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (133, 'مسدود کردن سپرده با مبلغي بيش از موجودي سپرده', 'سپرده ها', 'D-13-14', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (134, 'عمليات کارمزد صدور گواهينامه عدم پرداخت، دريافت', 'چکاوک', 'k-8-2', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (135, 'برداشت مستقيم- عمليات واريز به سپرده', 'پايا', 'p-13-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (136, 'برداشت مستقيم- عمليات برداشت از سپرده', 'پايا', 'p-14-1', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (137, 'صدور سند انتقال کارمزد آفلاين به هزينه هاي سپرده', 'سپرده ها', 'D-168-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (138, 'مديريت اسناد – تغيير سقف مجاز صدور سند براي گروه هاي کاربري', 'حسابداري', 'A-154-3', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (139, 'برداشت از سپرده - نقد کردن چک برگشتي با دليلي غير از کسر موجودي', 'سپرده ها', 'D-12-17', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (140, 'عمليات کارمزد ثبت چک عادي، دريافت', 'چکاوک', 'k-8-3', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (141, 'عمليات کارمزد ثبت چک رمزدار، دريافت', 'چکاوک', 'k-8-4', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (142, 'افتتاح سپرده با مشتري حقوقي مرتبط در شرف تاسيس', 'سپرده ها', 'D-10-7', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (143, 'عمليات کارمزد صدور چک رمزدار، دريافت', 'چکاوک', 'k-8-1', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (144, 'خزانه داري صياد، چاپ چک', 'چکاوک', 'k-9-1', 'چک');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (145, 'بستن سپرده - صدور چک', 'سپرده ها', 'D-14-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (146, 'مديريت اسناد', 'حسابداري', 'A-154-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (147, 'افتتاح سپرده حقيقي - نقدي', 'سپرده ها', 'D-10-2', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (148, 'افتتاح سپرده حقوقي - نقدي', 'سپرده ها', 'D-10-5', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (149, 'افتتاح سپرده نزدبانک - نقدي', 'سپرده ها', 'D-10-11', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (150, 'واريز به سپرده - وجه نقد', 'سپرده ها', 'D-11-1', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (151, 'واريز به سپرده - واگذاري چک - کارمزد نقدي', 'سپرده ها', 'D-11-3', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (152, 'مديريت صندوقها-بستن صندوق', 'حسابداري', 'A-11-5', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (153, 'مديريت صندوقها-انتقال موجودي بين صندوقها', 'حسابداري', 'A-11-8', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (154, 'صدور دسته چک - هزينه نقدي', 'سپرده ها', 'D-18-6', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (155, 'مديريت صندوقها-صدور سند فزوني صندوق', 'حسابداري', 'A-11-12', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (156, 'مديريت صندوقها-صدور سند کسري صندوق', 'حسابداري', 'A-11-13', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (157, 'برداشت از سپرده - وجه نقد', 'سپرده ها', 'D-12-1', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (158, 'برداشت از سپرده -پرداخت قسمتي از وجه -  نقدي', 'سپرده ها', 'D-12-4', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (159, 'بستن سپرده - نقدي', 'سپرده ها', 'D-14-2', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (160, 'صدور دفترچه سپرده - کارمزد نقدي', 'سپرده ها', 'D-16-2', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (161, 'صدور برگ سپرده - هزينه ابطال تمبر نقدي', 'سپرده ها', 'D-17-2', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (162, 'صدور دستور پرداخت - کارمزد نقدي', 'سپرده ها', 'D-18-2', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (163, 'مديريت چک عمومي-تخصيص چک عمومي به سپرده با کارمزد نقدي', 'سپرده ها', 'D-95-2', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (164, 'صدور دستور پرداخت - کارمزد نقدي', 'سپرده ها', 'D-81-6', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (165, 'صدور دسته چک - هزينه نقدي', 'سپرده ها', 'D-81-10', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (166, 'عمليات خزانه داري', 'حسابداري', 'A-37-0', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (167, 'عمليات خزانه داري- ارسال وجه نقد به ساير شعب', 'حسابداري', 'A-37-1', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (168, 'عمليات خزانه داري - ارسال وجه نقد به ساير بانک ها', 'حسابداري', 'A-37-2', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (169, 'عمليات خزانه داري - دريافت وجه نقد از ساير شعب', 'حسابداري', 'A-37-3', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (170, 'عمليات خزانه داري - تسويه وجوه در راه دريافتي از ساير بانک ها', 'حسابداري', 'A-37-7', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (171, 'عمليات خزانه داري - ارسال وجه نقد به ساير شعب به صورت گروهي', 'حسابداري', 'A-37-8', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (172, 'عمليات خزانه داري - دريافت وجه نقد از ساير شعب به صورت گروهي', 'حسابداري', 'A-37-9', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (173, 'واريز به سپرده - واريز وجه نقد با شماره مرجع پرداخت', 'سپرده ها', 'D-11-11', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (174, 'مديريت صندوقها-انتقال موجودي به صندوق خزانه دار', 'حسابداري', 'A-11-14', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (175, 'برداشت از سپرده - برداشت وجه نقد با شماره مرجع پرداخت', 'سپرده ها', 'D-12-15', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (176, 'پرداخت قسمتي از وجه چک / دستور پرداخت و صدور گواهينامه عدم پرداخت چک', 'سپرده ها', 'D-12-19', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (177, 'مديريت صندوقها-انتقال موجودي به صندوق ساير کاربران', 'حسابداري', 'A-11-15', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (178, 'مديريت صندوقها-افتتاح صندوق', 'حسابداري', 'A-11-4', 'نقدی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (179, 'افتتاح سپرده', 'سپرده ها', 'D-10-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (180, 'واريز به سپرده', 'سپرده ها', 'D-11-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (181, 'واريز به سپرده - واگذاري چک - کارمزد نقدي انتقالي', 'سپرده ها', 'D-11-8', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (182, 'صدور دفترچه - کار مزد نقدي انتقالي', 'سپرده ها', 'D-16-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (183, 'صدور برگ سپرده - هزينه ابطال تمبر نقدي انتقالي', 'سپرده ها', 'D-17-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (184, 'صدور دستور پرداخت - کارمزد نقدي انتقالي', 'سپرده ها', 'D-18-4', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (185, 'برداشت از سپرده', 'سپرده ها', 'D-12-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (186, 'انسداد سپرده', 'سپرده ها', 'D-13-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (187, 'بستن سپرده', 'سپرده ها', 'D-14-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (188, 'صدور دستور پرداخت', 'سپرده ها', 'D-18-0', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (189, 'صدور دستور پرداخت - کار مزد نقدي انتقالي', 'سپرده ها', 'D-81-8', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (190, 'صدور دسته چک - هزينه نقدي انتقالي', 'سپرده ها', 'D-81-12', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (191, 'برداشت از سپرده - وصول چک با مبلغ بزرگتر از مبلغ مندرج روي آن', 'سپرده ها', 'D-12-8', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (192, 'برداشت از سپرده - وصول چک با مشخصات مخالف اظهار صاحب سپرده', 'سپرده ها', 'D-12-9', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (193, 'واريز به سپرده - انتقال وجه با شماره مرجع پرداخت', 'سپرده ها', 'D-11-12', 'انتقالی');
INSERT INTO okmdb.dms_transaction (id, DESCRIPTION, SUBSYSTEM_NAME, TRANSACTION_CODE, DOCUMENT_CLASS) VALUES (194, 'صدور دسته چک - هزينه نقدي انتقالي', 'سپرده ها', 'D-18-8', 'انتقالی');
