package com.sima.dms.domain.enums;

public enum DocumentConflictReasonEnum {

    NON_ATTACHMENT_PROCEEDING_CURRENCY_STATISTIC,
    REVERSAL_SIGNATURE_PROCEEDING_CURRENCY_STATISTIC,
    NON_ATTACHMENT_PROCEEDING_USERS,
    STRIKE_THROUGH_DOCUMENT_OR_UNDERWRITE_LACKING,
    LACKING_DOCUMENT_PARAPHRASE,
    MISTAKE_IN_PARAPHRASE_DOCUMENT,
    USING_COLORFUL_PEN,
    LACKING_AUTHORITIES_SIGNATURE_IN_FORMS,
    LACKING_STAFF_SIGNATURE_IN_FORMS,
    LACKING_IN_REGISTER_DOCUMENT_CONTENT,
    PUNCHING_CHECKS,
    PUNCHING_FORMS,
    LACKING_SIGNATURE_PROCEEDING_USERS,
    }