package com.sima.dms.domain.enums;

public enum DocumentSetConflictReasonEnum {

    DOCS_NON_ATTACHMENT_SEAL,
    DOCS_SEAL_BREAK,
    DOCS_UNCLEAR_SEAL,
    DOCS_NON_ATTACHMENT_IN_SPECIFIED_PLACE,
    DOCS_NON_USES_CORRECT_PUNCH_NUMBER,
    DOC_OUT_OF_LINE_THREAD_PULLER,
    DOCS_NON_MATCHING_NAME_AND_CODE_ON_UNIT_INCLUDED_WITH_REQUeST_REGISTER,
    DOCS_NON_ROWS_NUMBER_ON_UNIT_INCLUDED_WITH_REQUeST_REGISTER,
    DOCS_NON_DATE_ON_UNIT_INCLUDED_WITH_REQUeST_REGISTER,
}
